# **Data Preprocessing**

In [138]:
import pandas as pd
import numpy as np

In [139]:
dataset = pd.read_csv('Placement_Data_Full_Class.csv')

In [140]:
dataset

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [141]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [142]:
dataset['status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

## **Seperate Features and Target**

* Features -> Columns

* Target -> Status

In [143]:
dataset

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [144]:
X = dataset.drop(['status','salary'],axis=1)
y = dataset.iloc[:,-2]

In [145]:
X

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p  
0     Sci&Tech     No     55.0         Mkt&HR  58.80  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50  
..         ...    ...      ...            ...    ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  

[215 rows x 13 columns]

In [146]:
y

0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...    
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object

## **Converting to an Array**

In [147]:
X = X.to_numpy()

In [148]:
y = y.to_numpy()

# Encoding


## **One Hot Encoder For Features**


In [149]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [150]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1,3,5,6,8,9,11])], remainder='passthrough')

In [151]:
X = np.array(ct.fit_transform(X))

In [152]:
X

array([[0.0, 1.0, 0.0, ..., 58.0, 55.0, 58.8],
       [0.0, 1.0, 1.0, ..., 77.48, 86.5, 66.28],
       [0.0, 1.0, 1.0, ..., 64.0, 75.0, 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 73.0, 59.0, 69.72],
       [1.0, 0.0, 0.0, ..., 58.0, 70.0, 60.23],
       [0.0, 1.0, 1.0, ..., 53.0, 89.0, 60.22]], dtype=object)

In [153]:
temp= pd.DataFrame(data=X)

In [154]:
temp

0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15   16     17     18     19  \
0    0  1  0  1  0  1  0  1  0  0  ...  1  0  0  1    1     67     91     58   
1    0  1  1  0  0  1  0  0  1  0  ...  0  1  1  0    2  79.33  78.33  77.48   
2    0  1  1  0  1  0  1  0  0  1  ...  1  0  1  0    3     65     68     64   
3    0  1  1  0  1  0  0  0  1  0  ...  1  0  0  1    4     56     52     52   
4    0  1  1  0  1  0  0  1  0  1  ...  1  0  1  0    5   85.8   73.6   73.3   
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. ..  ...    ...    ...    ...   
210  0  1  0  1  0  1  0  1  0  1  ...  1  0  1  0  211   80.6     82   77.6   
211  0  1  0  1  0  1  0  0  1  0  ...  1  0  1  0  212     58     60     72   
212  0  1  0  1  0  1  0  1  0  1  ...  0  1  1  0  213     67     67     73   
213  1  0  0  1  0  1  0  1  0  1  ...  1  0  0  1  214     74     66     58   
214  0  1  1  0  0  1  0  0  1  1  ...  1  0  0  1  215     62     58     53   

       20     21  
0      55   58.8  
1    86.5  66.28  
2      75   57.8  
3      66  59.43  
4    96.8   55.5  
..    ...    ...  
210    91  74.49  
211    74  53.62  
212    59  69.72  
213    70  60.23  
214    89  60.22  

[215 rows x 22 columns]

# Splitting data into train and test set

In [155]:
from sklearn.model_selection import train_test_split

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Label Encoder For Target  

In [157]:
from sklearn.preprocessing import LabelEncoder 

In [158]:
le = LabelEncoder()

In [159]:
y1_train  = le.fit_transform(y_train)

In [160]:
y1_test = le.fit_transform(y_test)

## **Standardization**


In [161]:
from sklearn.preprocessing import StandardScaler

In [162]:
sc = StandardScaler()

In [163]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## **Apply on Different Classification Algorithms**

* LogisticRegression

* KNeighborsClassifier

* DecisionTreeClassifier

* RandomForestClassifier

* SVC

In [164]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [165]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel = 'linear')
ks_cla = SVC(kernel = 'rbf')

In [166]:
l_cla.fit(X_train, y1_train)
k_cla.fit(X_train, y1_train)
d_cla.fit(X_train, y1_train)
r_cla.fit(X_train, y1_train)
s_cla.fit(X_train, y1_train)
ks_cla.fit(X_train, y1_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [167]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test) 

In [168]:
from sklearn.metrics import confusion_matrix

In [169]:
l_c = confusion_matrix(y1_test, l_pred)
k_c = confusion_matrix(y1_test, k_pred)
d_c = confusion_matrix(y1_test, d_pred)
r_c = confusion_matrix(y1_test, r_pred)
s_c = confusion_matrix(y1_test, s_pred)
ks_c = confusion_matrix(y1_test, ks_pred)

In [170]:
l_c

array([[10,  6],
       [ 2, 25]], dtype=int64)

In [171]:
k_c

array([[ 9,  7],
       [ 2, 25]], dtype=int64)

In [172]:
d_c

array([[ 8,  8],
       [ 2, 25]], dtype=int64)

In [173]:
r_c

array([[ 9,  7],
       [ 2, 25]], dtype=int64)

In [174]:
s_c

array([[11,  5],
       [ 2, 25]], dtype=int64)

In [175]:
ks_c

array([[ 9,  7],
       [ 0, 27]], dtype=int64)

# **Result**

In [176]:
from sklearn.metrics import accuracy_score

In [177]:
l_a = accuracy_score(y1_test, l_pred)
k_a = accuracy_score(y1_test, k_pred)
d_a = accuracy_score(y1_test, d_pred)
r_a = accuracy_score(y1_test, r_pred)
s_a = accuracy_score(y1_test, s_pred)
ks_a = accuracy_score(y1_test, ks_pred)

In [178]:
print('Logistic Regression: ' + str(l_a) + '\nKNeighbors: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.813953488372093
KNeighbors: 0.7906976744186046
Decision Tree: 0.7674418604651163
Random Forest: 0.7906976744186046
Linear SVC: 0.8372093023255814
Kernel SVC: 0.813953488372093


# **Conclusion**
## Linear SVC Algorithm gave the best result